development:
  adapter: postgresql
  database: medapulse_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: medapulse_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: medapulse
  pool: 5
  timeout: 5000
